apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rca-access
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rca-access-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: rca-access
  apiGroup: rbac.authorization.k8s.io

