apiVersion: v1
kind: Service
metadata:
  name: {{ include "orca.fullname" . }}
  labels:
{{ include "orca.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http-api
  selector:
    app.kubernetes.io/name: {{ include "orca.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
