{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "orca.serviceAccountName" . }}
  labels:
{{ include "orca.labels" . | indent 4 }}
{{- end -}}
